/* Generated by BIN2S - please don't edit directly */
#pragma once
#include <stddef.h>
#include <stdint.h>

extern const uint8_t acgc_3ds_vshader_shbin[];
extern const uint8_t acgc_3ds_vshader_shbin_end[];
#if __cplusplus >= 201103L
static constexpr size_t acgc_3ds_vshader_shbin_size=260;
#else
static const size_t acgc_3ds_vshader_shbin_size=260;
#endif
